fmod MYINT is
sort Int .
	op 0 : -> Int .
	op s_ : Int -> Int .
	op p_ : Int -> Int .
	op _+_ : Int Int -> Int .
	op _-_ : Int Int -> Int .
	op _*_ : Int Int -> Int .
	op _>_ : Int Int -> Int .
	op _<_ : Int Int -> Int .
	op _<=_ : Int Int -> Int .
	op _>=_ : Int Int -> Int .
	vars N M : Int .
	eq s(p(N)) = N . 
	eq p(s(N)) = N .
	eq 0 + M = M .
	eq N - 0 = N .
	eq M * 0 = 0 . 
	eq s(N) - M = s(N - M) .
	eq p(N) - M = p(N - M) .
	eq s(N) + M = s(N + M) .
	eq p(N) + M = p(N + M) .
endfm